---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update package manager
      when: "ansible_pkg_mgr == 'apt'"
      apt:
        update_cache: true
  roles:
    - role: keepass
      vars:
        keepass_plugins:
          - keepass2-plugin-tray-icon
